apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-api-service-monitor
  namespace: rollout-ramp-monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-api
  namespaceSelector:
    matchNames:
      - rollout-ramp-monitoring
      - default
  # The namespaceSelector allows the ServiceMonitor to discover services in both the monitoring namespace and the default namespace.
  endpoints:
  - port: http
    path: /metrics
    interval: 15s