# YAML definition of a Kubernetes Service for a Flask API application with Prometheus monitoring enabled.
apiVersion: v1
kind: Service
metadata:
  name: flask-api-metrics-monitoring
  labels:
    app: flask-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: flask-api
  ports:
  - name: http
    port: 80
    targetPort: 5000  
  type: ClusterIP