# This file defines a Kubernetes deployment for a Flask API application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api 
spec:
  replicas: 2
  selector:
      matchLabels:
        app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: northamerica-northeast2-docker.pkg.dev/advance-display-462217-r9/flask-api-repo/flask-api:latest
        env:
        - name: ABUSEIPDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: abuseipdb-secret
              key: ABUSEIPDB_API_KEY
        ports:
        - containerPort: 5000
        

